#
# generate-wsl-binds.ps1
#
# Detects installed WSL distros and generates a .wsl.tmux.conf containing
# keybindings for each one. Slot numbers follow the order that `wsl --list`
# returns, which is stable for a given machine state (deterministic, though
# not strictly by install date). No state file is needed.
#
# The generated file is gitignored (machine-specific) and copied into the
# tmux WSL distro by install-tmux-container.ps1 and update-config-tmux-container.ps1.
# ~/.tmux.conf sources it via `source-file -q`, which silently skips the file
# if it does not exist - safe on non-Windows tmux installations.
#
# Parameters:
#   -OutputPath : destination for the generated config file
#

[CmdletBinding()]
param(
    [string] $OutputPath = "$PSScriptRoot\.wsl.tmux.conf"
)

# Distros managed by these scripts that already have fixed bindings in .tmux.conf
$SkipDistros = @("tmux")

# Slots 1-3 are reserved in .tmux.conf (pwsh, cmd, powershell)
$FirstSlot = 4

# Resolve the default username and home directory for a WSL distro without
# invoking wsl.exe, which would inherit the calling WSL user's context and
# look up the wrong user in the target distro. Instead, read directly from:
#   - HKCU registry: DefaultUid stored per distro
#   - \\wsl.localhost\<distro>\etc\passwd: UID → username + home mapping
function Get-WslDistroUser {
    param([string] $DistroName)

    $DistroKey = Get-ChildItem "HKCU:\Software\Microsoft\Windows\CurrentVersion\Lxss" |
        Where-Object { $_.GetValue("DistributionName") -eq $DistroName } |
        Select-Object -First 1

    if (!$DistroKey) { return $null }

    $DefaultUid = $DistroKey.GetValue("DefaultUid")
    if ($null -eq $DefaultUid) { return $null }

    $Passwd = Get-Content "\\wsl.localhost\$DistroName\etc\passwd" -ErrorAction SilentlyContinue
    if (!$Passwd) { return $null }

    $Entry = $Passwd | Where-Object { ($_ -split ':')[2] -eq [string]$DefaultUid } | Select-Object -First 1
    if (!$Entry) { return $null }

    $Parts = $Entry -split ':'
    return [PSCustomObject]@{ Username = $Parts[0]; Home = $Parts[5] }
}

# Enumerate installed WSL distros in the order wsl --list returns them.
# wsl --list --quiet output can be UTF-16 LE with embedded nulls on some builds;
# the Trim + replace cleans that up.
$InstalledDistros = wsl --list --quiet 2>&1 |
    ForEach-Object { ($_.ToString()).Trim() -replace '\x00', '' } |
    Where-Object { $_ -match '\S' -and $SkipDistros -notcontains $_ }

$Lines = @("# Auto-generated by generate-wsl-binds.ps1 - do not edit manually")

if (!$InstalledDistros) {
    Write-Warning "No additional WSL distros found; generating empty .wsl.tmux.conf"
    # Note: Tmux config uses LF, not CRLF
    [System.IO.File]::WriteAllText($OutputPath, ($Lines -join "`n") + "`n", [System.Text.UTF8Encoding]::new($false))
    return
}

for ($i = 0; $i -lt $InstalledDistros.Count; $i++) {
    $Distro = $InstalledDistros[$i]
    $Slot   = $FirstSlot + $i

    Write-Host "Resolving default user for '$Distro'..."
    $DistroUser = Get-WslDistroUser -DistroName $Distro

    if (!$DistroUser) {
        Write-Warning "Could not resolve default user for '$Distro', skipping"
        continue
    }

    $WslCmd = "wsl.exe -d $Distro -u $($DistroUser.Username) --cd $($DistroUser.Home)"

    $Lines += ""
    $Lines += "# $Distro - $($DistroUser.Username) (C-F$Slot / C-s $Slot / M-$Slot)"
    $Lines += "bind -n C-F$Slot new-window `"$WslCmd`""
    $Lines += "bind -T switch-pane-keys $Slot split-window `"$WslCmd`"\; last-pane\; kill-pane\; select-layout even-vertical\; respawn-pane -k"
    $Lines += "bind -T switch-pane-keys M-$Slot split-window `"$WslCmd`""
    $Lines += "bind -T zip-through-keys C-F$Slot send-keys C-F$Slot"
}

# Note: Tmux config uses LF, not CRLF
[System.IO.File]::WriteAllText($OutputPath, ($Lines -join "`n") + "`n", [System.Text.UTF8Encoding]::new($false))
Write-Host "Generated .wsl.tmux.conf for: $($InstalledDistros -join ', ')"
